heroku/heroku-buildpack-java

README.md

Closes Issue #61 adding featured image to readme, mostly for Elements Marketplace. cc @craigkerstiens

Update README.md with Featured Image

---

README.md

update Java image in Readme

---

bin/compile
bin/test
bin/test-compile
lib/common.sh
lib/maven.sh
test/common_test.sh
test/compile_test.sh
test/detect_test.sh
test/release_test.sh
test/stdlib_stubs.sh
test/test_test.sh

Add buildpack stdlib

---

lib/common.sh

Includes a fix for the BUILDPACK_LOG_FILE default

Upgraded stdlib to v7 to fix #77

---

lib/common.sh
vendor/maven/sources.txt

Download Maven over HTTPS

---

Gemfile.lock
README.md
bin/detect
hatchet.json
spec/maven_spec.rb
test/detect_test.sh

Replaces #85 in order to run private integration tests

Add support for Maven Polyglot POM formats (internal)

---

bin/compile
circle.yml

This will log metrics for apps using Kotlin and Groovy.

Added mcount of kotlin and groovy files in the repo

---

bin/test
lib/maven.sh
spec/db_spec.rb
spec/java_spec.rb
spec/maven_spec.rb
spec/spring_spec.rb
test/compile_test.sh

Use Maven settings.xml in Testpack script

---

CHANGELOG.md
bin/test
test/test_test.sh

Add support for MAVEN_HEROKU_CI_GOAL during bin/test

---

.circleci/config.yml
CHANGELOG.md
test/spec/java_spec.rb

Fixes [W-8232831](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008F5ntIAC/view)

Enable heroku-20 testing

---

CHANGELOG.md

Closes [W-8436129](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008iywJIAQ/view)

Prepare v68 release

---

CHANGELOG.md
buildpack.toml

Port of https://github.com/heroku/heroku-buildpack-jvm-common/pull/190/

Upgrade CNB API to 0.4 and use semver

---

CHANGELOG.md

To pick up #182, #183 & #184.
GUS-W-11283397.

Release v72

---

CHANGELOG.md
README.md
lib/common.sh
test/common_test.sh
test/compile_test.sh
test/helpers.sh
test/spec/maven_spec.rb

Upgrade default Maven version to `3.9.4`

---

.github/workflows/ci.yml
test/compile_test.sh
test/helpers.sh
test/spec/db_spec.rb
test/spec/fixtures/repos/java-apache-dbcp-sample/pom.xml
test/spec/java_spec.rb
test/spec/maven_spec.rb
test/spec/spec_helper.rb

Various fixes that were required to get CI working again. Some changes were general CI fixes unrelated to Heroku 24.
Closes GUS-W-15902052

Add heroku-24 to CI

---

bin/compile
bin/release
lib/buildpack-stdlib-v7.sh
lib/common.sh
lib/frameworks.sh
lib/maven.sh

Fix shellcheck linting errors. CI check for shellcheck will be implemented separately.

Fix shellcheck linting errors

---

.github/workflows/ci.yml
Gemfile
Makefile
bin/release
bin/test
bin/test-compile
etc/publish.sh
test/spec/settings_xml_spec.rb
test/spec/smoke_spec.rb
test/spec/spec_helper.rb
test/spec/versions_spec.rb

Ports the CI improvements and Makefile from `heroku/jvm` to this repo. A couple of extra lint and style fixes needed to happen at the same time to make CI pass.

CI Improvements

---

bin/test
bin/test-compile

This is a quick fix for #236 to unblock the user right away. There will be a follow-up PR with improvements to CI to catch such issues before merging to main.

Add missing `util.sh` to `bin/test{-compile}`

---

bin/test

Remove quoting of Maven opts in `bin/test`

---

bin/test
test/spec/heroku_ci_spec.rb

Add Heroku CI smoke test and fix quoting issue in `bin/test`.

Add Heroku CI smoke test
