- bin/release
This will allow the lowest available plan to be selected  by default as opposed to the hard coded one today.
> Changing to not hard add-on code plan

- .travis.yml
- bin/release
- etc/hatchet-test.sh
To avoid detecting JAR files in `target/dependency` and such.
> Added -maxdepth to find command in bin/release

- bin/compile
- bin/test
- bin/test-compile
The earlier use was incorrect, and resulted in nothing being exported. I'm surprised it didn't error out though.
> Use export_env function correctly

- etc/hatchet.sh
- lib/common.sh
Double quote array expansions, otherwise they're like `$*` and break on spaces.
Use `"${var:?}"` to ensure this never expands to `/` .
> Fix some Bash issues

- bin/test
- test/test_test.sh
According to https://devcenter.heroku.com/articles/testpack-api the right signature is `/bin/test BUILD_DIR ENV_DIR`
> /bin/test has only 2 parameters

- lib/maven.sh
- test/test_test.sh
`/bin/test-compile` is hardcoding `$BUILD_DIR` into `$HOME/.profile.d/maven.sh`
This patch will potspone use `$HOME` instead.
>  Don't hardcode $BUILD_DIR in maven profile

- CHANGELOG.md
- bin/compile
- lib/common.sh
- test/compile_test.sh
Pass cache_dir to jvm buildpack so that `system.properties` file can be cached
See https://github.com/heroku/heroku-buildpack-jvm-common/pull/82
> Cache JVM Version

- CHANGELOG.md
- lib/maven.sh
This change enables support for using the [Maven wrapper without a binary JAR](https://github.com/takari/maven-wrapper#usage-without-binary-jar).
Fixes #121
> Remove check for .mvn/wrapper/maven-wrapper.jar 

- spec/java_spec.rb
Java 1.6 support was removed from `heroku/jvm` causing this Hatchet spec to fail. Since we do not support 1.6 anymore, there is no replacement required for this spec.
> Remove Hatchet spec for Java 1.6 [changelog skip]

- CHANGELOG.md
- buildpack.toml
[This RFC](https://github.com/buildpacks/rfcs/pull/40) is working its way through and it seems useful to be able to use Heroku buildpacks on `cloudfoundry/cnb:bionic`. This also aligns with how riff is compatible with [multiple stacks](https://github.com/projectriff/node-function-buildpack/blob/master/buildpack.toml#L22).
> Add io.buildpacks.stacks.bionic as supported stack [changelog skip]

- .travis.yml
- Gemfile
- Gemfile.lock
- spec/java_spec.rb
- spec/spec_helper.rb
- ActiveSupport's Object#blank? and Object#present? are no longer provided by default (https://github.com/heroku/hatchet/pull/107)
- Remove deprecated support for passing a block to `App#run` (https://github.com/heroku/hatchet/pull/105)
- Ignore  403 on app delete due to race condition (https://github.com/heroku/hatchet/pull/101)
- The hatchet.lock file can now be locked to "main" in addition to "master" (https://github.com/heroku/hatchet/pull/86)
- Allow concurrent one-off dyno runs with the `run_multi: true` flag on apps (https://github.com/heroku/hatchet/pull/94)
- Apps are now marked as being "finished" by enabling maintenance mode on them when `teardown!` is called. Finished apps can be reaped immediately (https://github.com/heroku/hatchet/pull/97)
- Applications that are not marked …
> [changelog skip] Hatchet v7.0.0

- buildpack.toml
Adds support for the `heroku/heroku:20` stack to the CNB implementation of this buildpack.
> Add heroku-20 stack to CNB buildpack.toml [skip-changelog]

- CHANGELOG.md
- bin/compile
- bin/test
- bin/test-compile
- lib/buildpack-stdlib-v7.sh
- lib/common.sh
- test/compile_test.sh
- test/spec/db_spec.rb
- test/spec/java_spec.rb
- test/spec/maven_spec.rb
- test/spec/spring_spec.rb
Since:
- The buildpack-stdlib repo has been sunset/archived, so no future changes to it are expected.
- It's a script rather than a binary and is a small file, so a great candidate for vendoring.
- Downloading it at runtime causes more potential failures modes, as seen in https://github.com/heroku/heroku-buildpack-clojure/pull/118
GUS-W-11283397.
> Vendor buildpack-stdlib

- CHANGELOG.md
- lib/common.sh
- test/common_test.sh
Whilst the global S3 endpoint (`s3.amazonaws.com`) still works, AWS now recommends using the appropriate regional endpoint to access the bucket:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#s3-legacy-endpoints
Our buildpack buckets are in `us-east-1`, whose regional domain is `*.s3.us-east-1.amazonaws.com`:
https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_region
GUS-W-11283397.
> Switch to the recommended regional S3 domain

- .circleci/config.yml
- CHANGELOG.md
- lib/common.sh
- lib/maven.sh
- test/spec/agent_spec.rb
In the shimmed CNBs used in `heroku/builder` we have been seeing quite a few transient errors related to buildpacks downloading from S3.
Adding appropriate retries and connection timeouts to all of our buildpack's curl usages should help with these, as well as make builds more reliable in general for users on Heroku, plus also anyone using a shimmed CNB locally with Pack CLI (where the network connection may be even less reliable).
The `--retry-connrefused` option has been used since otherwise curl doesn't retry cases where the connection was refused. Ideally we would use `--retry-all-errors` which takes that one step further, however that option was only added in curl 7.71, so is only supported by Heroku-22+.
For more on curl options, see:
https://curl.se/docs/manpage.html …
> Adjust curl retry and connection timeout handling

- .github/workflows/check_changelog.yml
- .github/workflows/ci.yml
- CHANGELOG.md
Since the Heroku-18 stack has reached end-of-life, and as such builds using it are no longer supported by the Heroku build system:
https://devcenter.heroku.com/changelog-items/2583
This fixes the integration tests failing in CI for the Heroku-18 stack, due to the build system now (as expected) rejecting the jobs.
Any non-Heroku consumers of this buildpack that wish to continue using the Heroku-18 stack should pin to the previous version of this buildpack.
Ref: GUS-W-10446298
> Remove heroku-18 stack support

- CHANGELOG.md
- bin/release
- lib/frameworks.sh
QOL improvement for when users initially set up a Quarkus or Micronaut app. It picks the correct build task and sets a default web process type if no `Procfile` is present. This is the same mechanism we use for the other frameworks.
> Add Micronaut and Quarkus support

- bin/compile
- bin/detect
- bin/release
- bin/test
- bin/test-compile
- etc/publish.sh
- lib/buildpack-stdlib-v7.sh
- lib/common.sh
- lib/frameworks.sh
- lib/maven.sh
Apply shfmt formatting. CI check for formatting will be implemented separately.
> Apply shfmt formatting

- CHANGELOG.md
- lib/maven.sh
- test/spec/misc_spec.rb
Before #257, invalid Maven wrapper installations were silently ignored. The refactor removed that logic to make issues apparent should they still exist. As it turns out a much larger percentage of applications have broken Maven wrapper installations than expected. To aid these users with fixing their Maven Wrapper installation, this PR add explicit validation again and provides a clear error message when a broken installation was detected.
* Add Maven Wrapper validation with clear error message when required files are missing
GUS-W-19546430
> Validate Maven Wrapper installation

- CHANGELOG.md
- lib/maven.sh
- test/spec/misc_spec.rb
Changes incomplete Maven Wrapper setup from a build-failing error to a warning when the maven-wrapper.properties file is missing but the mvnw script exists. Maven builds now continue instead of failing when properties file is missing by using the Heroku Maven default version. This is consistent with buildpack behaviour before the latest refactoring work.
The error message as been reworded to be a warning with additional information how and when to fix this issue. This warning will become an error eventually.
GUS-W-19581154
> Change Maven Wrapper validation from error to warning
